export const counterpartybankaccountPermissions = {
  view: "COUNTERPARTY_BANK_ACCOUNT_VIEW",
  detail: "COUNTERPARTY_BANK_ACCOUNT_VIEW_DETAIL",
  create: "COUNTERPARTY_BANK_ACCOUNT_CREATE",
  update: "COUNTERPARTY_BANK_ACCOUNT_UPDATE",
  delete: "COUNTERPARTY_BANK_ACCOUNT_DELETE",
} as const;
