export const edoEndpoints = {
  activeProvider: "/edo/active-provider",
  capabilities: "/edo/capabilities",
  authChallenge: "/edo/auth/challenge",
  authComplete: "/edo/auth/complete",
  fakturaAuthComplete: "/edo/auth/faktura/complete",
  outboxFacturas: "/edo/outbox/facturas",
  outboxSign: (id: string | number) => `/edo/outbox/${id}/sign`,
  inbox: "/edo/inbox",
  outbox: "/edo/outbox",
  allDocuments: "/edo/documents/all",
  document: (id: string | number) => `/edo/documents/${id}`,
  inboxSummary: "/edo/inbox/summary",
  inboxReject: (id: string | number) => `/edo/inbox/${id}/reject`,
  file: (id: string | number) => `/edo/files/${id}`,
  outboxStatus: (id: string | number) => `/edo/outbox/${id}/status`,
  remoteOutboxStatus: "/edo/outbox/status",
  inboxStatus: (id: string | number) => `/edo/inbox/${id}/status`,
} as const;
