export const paymentAcceptancePointOperationPermissions = {
  view: "PAYMENT_ACCEPTANCE_POINT_OPERATION_VIEW",
  detail: "PAYMENT_ACCEPTANCE_POINT_OPERATION_VIEW_DETAIL",
  create: "PAYMENT_ACCEPTANCE_POINT_OPERATION_CREATE",
  update: "PAYMENT_ACCEPTANCE_POINT_OPERATION_UPDATE",
  delete: "PAYMENT_ACCEPTANCE_POINT_OPERATION_DELETE",
} as const;
