export const purchasePermissions = {
  view: "PURCHASE_DOC_VIEW",
  detail: "PURCHASE_DOC_VIEW_DETAIL",
  create: "PURCHASE_DOC_CREATE",
  update: "PURCHASE_DOC_UPDATE",
  delete: "PURCHASE_DOC_DELETE",
  confirm: "CONFIRM_PURCHASE",
  cancel: "CANCEL_PURCHASE",
  lineView: "PURCHASE_DOC_TABLE_VIEW",
  lineDetail: "PURCHASE_DOC_TABLE_VIEW_DETAIL",
  lineCreate: "PURCHASE_DOC_TABLE_CREATE",
  lineUpdate: "PURCHASE_DOC_TABLE_UPDATE",
  lineDelete: "PURCHASE_DOC_TABLE_DELETE",
  reportView: "PURCHASE_REPORT_GET_ALL",
  reportDetail: "PURCHASE_REPORT_GET_BY_ID",
  reportExport: "PURCHASE_REPORT_EXPORT",
} as const;
