export const purchasePermission = {
  VIEW: "GOODSMOVEMENT_PURCHASE_VIEW",
  DETAILS: "GOODSMOVEMENT_PURCHASE_VIEW_DETAIL",
  CREATE: "GOODSMOVEMENT_PURCHASE_CREATE",
  PREPARE: "GOODSMOVEMENT_PURCHASE_PREPARE",
  CONFIRM: "GOODSMOVEMENT_PURCHASE_CONFIRM",
  UPDATE: "GOODSMOVEMENT_PURCHASE_UPDATE",
  DELETE: "GOODSMOVEMENT_PURCHASE_DELETE",
  SERIALNUMBERS: "GOODSMOVEMENT_PURCHASE_SERIALNUMBERS_VIEW",
  SEND_RECEIPT: "GOODSMOVEMENT_PURCHASE_SEND_CHECK",
};

export const basePurchasePermission = {
  VIEW: "GOODSMOVEMENT_PURCHASE_VIEW",
  CREATE: "GOODSMOVEMENT_PURCHASE_CREATE",
  ACCEPT: "GOODSMOVEMENT_PURCHASE_CONFIRM",
  DETAIL: "GOODSMOVEMENT_PURCHASE_VIEW_DETAIL",
};
