export const settingsEndpoints = {
  settings: {
    list: "/settings",
    detail: (id: string | number) => `/settings/${id}`,
    create: "/settings",
    update: (id: string | number) => `/settings/${id}`,
  },
  role: {
    list: "/roles",
    detail: (id: string | number) => `/roles/${id}`,
    modules: "/manual/module-sub-groups",
    create: "/roles",
    update: (id: string | number) => `/roles/${id}`,
  },
  users: {
    list: "/users",
    detail: (id: string | number) => `/users/${id}`,
    create: "/users",
    update: (id: string | number) => `/users/${id}`,
  },
  organizations: {
    list: "/organizations",
    detail: (id: string | number) => `/organizations/${id}`,
    create: "/organizations",
    update: (id: string | number) => `/organizations/${id}`,
  },
  counterparty: {
    list: "counterparty-cards",
    detail: (id: string | number) => `/counterparty-cards/${id}`,
    create: "counterparty-cards",
    update: (id: string | number) => `/counterparty-cards/${id}`,
  },
  departments: {
    list: "departments",
    detail: (id: string | number) => `/departments/${id}`,
    create: "departments",
    update: (id: string | number) => `/departments/${id}`,
  },
  branches: {
    list: "branches",
    detail: (id: string | number) => `/branches/${id}`,
    create: "branches",
    update: (id: string | number) => `/branches/${id}`,
  },
  chartAccounts: {
    list: "chart-accounts",
    detail: (id: string | number) => `/chart-accounts/${id}`,
    create: "chart-accounts",
    update: (id: string | number) => `/chart-accounts/${id}`,
  },
    counterpartyBankAccount: {
    list: "counterparty-bank-accounts",
    detail: (id: string | number) => `/counterparty-bank-accounts/${id}`,
    create: "counterparty-bank-accounts",
    update: (id: string | number) => `/counterparty-bank-accounts/${id}`,
  },
  orgBankAccounts: {
    list: "org-bank-accounts",
    detail: (id: string | number) => `/org-bank-accounts/${id}`,
    create: "org-bank-accounts",
    update: (id: string | number) => `/org-bank-accounts/${id}`,
  },
    positions: {
    list: "positions",
    detail: (id: string | number) => `/positions/${id}`,
    create: "positions",
    update: (id: string | number) => `/positions/${id}`,
  },
    productGroups: {
    list: "product-groups",
    detail: (id: string | number) => `/product-groups/${id}`,
    create: "product-groups",
    update: (id: string | number) => `/product-groups/${id}`,
  },
};
